tap "caskroom/cask"
cask "alfred"
cask "appcleaner"
cask "batchmod"
cask "cakebrew"
cask "google-japanese-ime"
cask "sublime-text"
cask "visual-studio-code"
cask "iterm2"
cask "minikube"
cask "java"
cask "postman"
cask "google-cloud-sdk"
cask "sequel-pro"
cask "spectacle"

